# src/CloudPod/ClassroomBundle/Resources/config/doctrine/LessonFileUploads.orm.yml
CloudPod\ClassroomBundle\Entity\ClassSubmissions:
  type:  entity
  table: class_submission
  id:
    submissionID:
      column: file_submission_id
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      column: file_submission_name
      type: string
      length: 255
      nullable: false
    path:
      column: file_submission_path
      type: text
    mimeType:
      column: mime_type
      type: text
    size:
      column: file_submission_size
      type: integer
    dynamicLoc:
      column: file_submission_dir
      type: integer
  lifecycleCallbacks:
    prePersist: [ preUpload ]
    postPersist: [ upload ]
    preUpdate: [ preUpload ]
    postUpdate: [ upload ]
    postRemove: [ removeUpload ]
  manyToMany:
    submittedBy:
      targetEntity: CloudPod\UserBundle\Entity\User
      joinTable:
        name: list_user_submissions
        joinColumns:
          submissionID:
            referencedColumnName: file_submission_id
        inverseJoinColumns:
          userID:
            referencedColumnName: user_id
            unique: true

