parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: CloudPodDB
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 0e73e2056b09b570000cbd0b7991749b4db091c9
    database_path: null
