parameters:
    security.interactive_login.listener.class: CloudPod\UserBundle\EventListener\LoginInteractive

services:
    security.interactive_login.listener:
        class: "%security.interactive_login.listener.class%"
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }