<?php

namespace Proxies\__CG__\CloudPod\ClassroomBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Lessons extends \CloudPod\ClassroomBundle\Entity\Lessons implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getLessonID()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["lessonID"];
        }
        $this->__load();
        return parent::getLessonID();
    }

    public function setLessonTitle($lessonTitle)
    {
        $this->__load();
        return parent::setLessonTitle($lessonTitle);
    }

    public function getLessonTitle()
    {
        $this->__load();
        return parent::getLessonTitle();
    }

    public function setLessonDesc($lessonDesc)
    {
        $this->__load();
        return parent::setLessonDesc($lessonDesc);
    }

    public function getLessonDesc()
    {
        $this->__load();
        return parent::getLessonDesc();
    }

    public function setLessonContent($lessonContent)
    {
        $this->__load();
        return parent::setLessonContent($lessonContent);
    }

    public function getLessonContent()
    {
        $this->__load();
        return parent::getLessonContent();
    }

    public function setLessonCreatedAt($lessonCreatedAt)
    {
        $this->__load();
        return parent::setLessonCreatedAt($lessonCreatedAt);
    }

    public function getLessonCreatedAt()
    {
        $this->__load();
        return parent::getLessonCreatedAt();
    }

    public function setLessonFileID(\CloudPod\ClassroomBundle\Entity\LessonFileUpload $lessonFileID = NULL)
    {
        $this->__load();
        return parent::setLessonFileID($lessonFileID);
    }

    public function getLessonFileID()
    {
        $this->__load();
        return parent::getLessonFileID();
    }

    public function addLessonClas(\CloudPod\ClassroomBundle\Entity\Classroom $lessonClass)
    {
        $this->__load();
        return parent::addLessonClas($lessonClass);
    }

    public function removeLessonClas(\CloudPod\ClassroomBundle\Entity\Classroom $lessonClass)
    {
        $this->__load();
        return parent::removeLessonClas($lessonClass);
    }

    public function getLessonClass()
    {
        $this->__load();
        return parent::getLessonClass();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'lessonID', 'lessonTitle', 'lessonDesc', 'lessonContent', 'lessonCreatedAt', 'lessonFileID', 'lessonClass');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}